vich_uploader:
  db_driver: orm

  mappings:
    offers: # On définit le nom du mapping. Il nous servira pour appeler cette configuration.
      uri_prefix: /images/offers # On définit ici le préfix de toutes nos images lié aux offres. On aura plus besoin de faire appel à 'images/offer/test.jpg', on pourra dirrectement appeler 'test.jpg'.
      upload_destination: "%kernel.project_dir%/public/images/offers" # L'endroit dans notre projet ou les images vont être stocké.
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # Donne un identifiants unique pour chaque photo uploadé.
    users:
      uri_prefix: /images/users 
      upload_destination: "%kernel.project_dir%/public/images/users" 
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer 

